# Generated by Django 4.2.7 on 2023-11-27 07:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("TenantApi", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
